language: scala

scala:
- 2.12.4

jdk:
- oraclejdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

env:
  global:
    JSENV=node

script:


deploy:
  provider: script
  script:
  - /bin/bash "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && sbt ++$TRAVIS_SCALA_VERSION publish
  on:
    tags: true

env:
  global:
  # travis encrypt BINTRAY_USER=xxx
  - secure: "Wh+UWd/Lijn1Fk6qIAf9S1YSCYAXmaL8e9yMBUG1pPzDRpfIEx9c2EsishJt9XQrINKDC3T1SOqixg302apdogKYCOD2q+y88yckaiEK4qyvugilnNU3ySMz6uNqEYcAmxk58j3lRdOBY+MAKrpoNzyHfX7HDa+6NWILhkPURc5Z5kCjuV8dkCQSnbrc2wkS0j9nqQBAykmgTMW6p6/HQOymPszk865uMqfql6Bnav0rixzc8IfcpaTxi2TMET7qxdJEYX8doOFwaUOQh8GRcbz4frms5GMpFBGSbvkujdOymHNCG4IXPjky10Lw3pckCfT/vU1ZneswTkR69iiawrIlAKPZVE68tpDMsHUXf91AJqnk52R6RJY5y1POeRoUf6uBrZ6mTBuBgyLmUk5GsnQhveCfI7RN5CCClFlurvZt/k85HcgnVXaj/qrKVCLpexd/oRqYhJaFV0I/zH2Ayn1Bh7akfY1sxTcrzueVs3zLHWIoAca1Ja+Wr1nFuR0IRPd3nfX3yiWhSr5CGBcqzgfo4rC95pXgxWG8GRl+VGv/VtFFZlaO5CVm1+PM52GHXps0i8DHLWfu2KuPUwq3CCsjaIvIlbjz2M8yIovQbMder7+NyJdW2/put7etJMXyAzymt4OqlHpN5QzY8BN0nWqKBtJGlQOfTXNzMyCC0L4="
  # travis encrypt BINTRAY_PASSWORD=xxx
  - secure: "j9j/3bvjE3NGACkr7aDFqUnSPmYYjAm425xtchWUT8Ov/PVdrgPtI1vwRsFMMhbh+58aSKbiOQ683wCHblgwN5OoXwmW8Hu5lt2rlm/lcK8fZ9YjqwIf+nbxcSjnK7cbdlZgW31cwIPqVUvnnkePyfCkV+r2AibjG6msV14GjsrY2WPqWIx4qUGx5LiYB+ipkI1b9eEuH8Q3lJHyTIFmJhUiVu0Ro3yHlEV3Z2jFdV/rY+sjGBCEBJJKoAJ6nuxPgV6yKc0181NIKB2FodnhV3eszci5bgJLGuHYoG4qnxGLnU12f26i3wZFnOqBbkNDp2j0rRaxQ6N167zwfZGiKDiWheVEk6NWcbaEP8ciz9exM5V5/HT+ciB1wNSRrfEVdW3LAa/DoTubZq9nVfb9U0GGbO4cFhbtVWyXgDYEvC5v7QzAnGWaxs2sJ43UcrXeyH3D3VNzfHEwylqKBMEsvwNgmTlWcgknZCRoddFkzRxDpymW47ibfmwzNjfvsyGvjoH7XyA+3u6HlRP53Yky/w1a/c4COZIm/Y4j2ht/7xh6DFVlmMllLXVhg9gItYFmBGu7c1oD8gs2NucOhq+G/VX/tLWqtZ3zDQBzoCR7H3Y16pgNCOE/3cw074mkxpVhJqbKnwWWgDXPGHsmYsa20YJfMAWDDkksCtqsx+nm7g4="

